name: Setup MySQL
inputs:
  mysql-version:
    description: The MySQL version to download (if necessary) and use
    required: true
  database:
    description: Database to create
    required: false
  username:
    description: Username for the database
    required: false
    default: ""
  password: 
    description: Password for the user
    default: ""
    required: false
runs:
  using: node12
  main: index.js
