name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            mysql-version: 8.0
          - os: windows-2019
            mysql-version: 5.6
    steps:
    - uses: ankane/setup-mysql@windows2
      with:
        mysql-version: ${{ matrix.mysql-version }}
    - run: mysql --version
    - run: mysqladmin create testdb
    - run: mysql -D testdb -e 'SELECT VERSION()'
