name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            mysql-version: 8.0
          - os: ubuntu-18.04
            mysql-version: 8.0
          - os: ubuntu-18.04
            mysql-version: 5.7
          - os: ubuntu-16.04
            mysql-version: 8.0
          - os: ubuntu-16.04
            mysql-version: 5.7
          - os: macos-11.0
            mysql-version: 8.0
          - os: macos-11.0
            mysql-version: 5.7
          - os: macos-11.0
            mysql-version: 5.6
          - os: macos-10.15
            mysql-version: 8.0
          - os: macos-10.15
            mysql-version: 5.7
          - os: macos-10.15
            mysql-version: 5.6
          - os: windows-2019
            mysql-version: 5.7
          - os: windows-2016
            mysql-version: 5.7
    steps:
    - uses: ankane/setup-mysql@v1
      with:
        mysql-version: ${{ matrix.mysql-version }}
    - run: mysql --version
    - run: mysqladmin create testdb
    - run: mysql -D testdb -e 'SELECT VERSION()'
