name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        mysql-version: [8.0, 5.7, 5.6]
        include:
          - os: ubuntu-20.04
            mysql-version: 8.0
          - os: ubuntu-18.04
            mysql-version: 8.0
          - os: ubuntu-18.04
            mysql-version: 5.7
          - os: ubuntu-16.04
            mysql-version: 8.0
          - os: ubuntu-16.04
            mysql-version: 5.7
    steps:
    - uses: ankane/setup-mysql@v1
      with:
        mysql-version: ${{ matrix.mysql-version }}
    - run: |
        mysqladmin create setup_mysql_test
        mysql -D setup_mysql_test -e 'SELECT VERSION()'
